import Foundation
import CryptoKit
import EPUB

/// Persists pre-reading briefings under
/// `~/Library/Application Support/Humanist/Briefings/<key>.json`,
/// keyed by the canonical path of the EPUB the briefing was
/// generated for. Same posture as `ChatTranscriptStore`:
///
///   * Stored outside the .epub so it survives if the user closes
///     without saving and doesn't conflate document state with
///     generated-overview state.
///   * Lossy writes (best-effort): a failed save just means the
///     next briefing re-streams; nothing user-visible breaks.
///   * Filename is SHA-256(canonicalPath) so renames within the
///     same path don't collide and the directory listing doesn't
///     leak book titles.
///
/// Briefings are essentially static for a given (book, library)
/// state — the user's stated case for caching them: "Retry handles
/// the cases where they aren't." So we deliberately don't fingerprint
/// the catalog or backend; cache hit on URL alone. The user invalidates
/// explicitly via the sheet's Retry button.
struct BookBriefingStore {
    private let baseDirectory: URL

    init(baseDirectory: URL? = nil) {
        if let baseDirectory {
            self.baseDirectory = baseDirectory
        } else {
            let support = FileManager.default.urls(
                for: .applicationSupportDirectory, in: .userDomainMask
            ).first ?? FileManager.default.temporaryDirectory
            self.baseDirectory = support
                .appendingPathComponent("Humanist", isDirectory: true)
                .appendingPathComponent("Briefings", isDirectory: true)
        }
    }

    /// Returns the cached briefing for `epubURL`, or nil when no
    /// cache exists (first-open) or the on-disk file is unreadable.
    /// The full `Payload` is returned so the sheet can surface
    /// "generated by X on date Y" if it wants to.
    func read(for epubURL: URL) -> Payload? {
        let url = fileURL(for: epubURL)
        guard FileManager.default.fileExists(atPath: url.path),
              let data = try? Data(contentsOf: url),
              let payload = try? Self.decoder.decode(Payload.self, from: data)
        else { return nil }
        return payload
    }

    /// Persist a freshly-generated briefing. Creates the storage
    /// directory on demand; encode/write failures are silent —
    /// next open just regenerates.
    func write(
        _ briefing: String,
        for epubURL: URL,
        backendIdentifier: String
    ) {
        let url = fileURL(for: epubURL)
        try? FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        let payload = Payload(
            version: 1,
            briefing: briefing,
            generatedAt: Date(),
            backendIdentifier: backendIdentifier
        )
        guard let data = try? Self.encoder.encode(payload) else { return }
        try? data.write(to: url, options: .atomic)
    }

    /// Delete the cached briefing for `epubURL`. Called when the
    /// user hits Retry so the next read miss and the post-stream
    /// save overwrites cleanly.
    func clear(for epubURL: URL) {
        let url = fileURL(for: epubURL)
        try? FileManager.default.removeItem(at: url)
    }

    private func fileURL(for epubURL: URL) -> URL {
        let canonical = epubURL.canonicalForFile.standardizedFileURL.path
        let digest = SHA256.hash(data: Data(canonical.utf8))
        let hex = digest.map { String(format: "%02x", $0) }.joined()
        return baseDirectory.appendingPathComponent("\(hex).json")
    }

    /// `version` lets a future schema change negotiate decode
    /// behavior; today every persisted file is version 1.
    /// `backendIdentifier` is e.g. "claude-sonnet-4-6" or
    /// "ollama:qwen3.5:9b" — surfaced in the sheet so the user
    /// can see which model produced the cached text and decide
    /// whether to Retry against a different model.
    struct Payload: Codable, Equatable {
        let version: Int
        let briefing: String
        let generatedAt: Date
        let backendIdentifier: String
    }

    private static let encoder: JSONEncoder = {
        let e = JSONEncoder()
        e.outputFormatting = [.prettyPrinted, .sortedKeys]
        e.dateEncodingStrategy = .iso8601
        return e
    }()

    private static let decoder: JSONDecoder = {
        let d = JSONDecoder()
        d.dateDecodingStrategy = .iso8601
        return d
    }()
}
