import Foundation

/// Per-figure machine-readable metadata generated by the
/// `DiagramExtractor` pipeline (P-Diagram-Description). Keyed
/// by `FigureAsset.id` on `Chapter.figureMetadata`.
///
/// The alt text already lives on the `Block.figure(alt:)` field
/// where the EPUB writer emits it as the `<img alt>` attribute;
/// `altText` is duplicated here so a downstream consumer
/// (chat indexer, library export, audit log) can read all
/// of the figure's metadata from one place without walking
/// the block stream.
///
/// `description` (Tier 2) is a longer paragraph (200–500 chars)
/// intended for the chat / search retrieval index. The XHTML
/// writer emits it inside a `<aside hidden>` next to the figure
/// so the existing paragraph-based indexer picks it up
/// automatically without the EPUB rendering it to the reader.
///
/// `labels` (Tier 3) are short text strings recognized inside
/// the diagram — axis labels, callouts, legend entries. Same
/// hidden-aside posture as `description`.
public struct FigureMetadata: Sendable, Equatable, Codable {
    public let altText: String
    public let description: String?
    public let labels: [String]

    public init(
        altText: String,
        description: String? = nil,
        labels: [String] = []
    ) {
        self.altText = altText
        self.description = description
        self.labels = labels
    }

    /// True when the metadata carries indexable content beyond
    /// the alt text — drives whether the XHTML writer bothers
    /// emitting a hidden `<aside>`. A metadata blob with only
    /// alt text doesn't need an aside because the alt already
    /// lives on the `<img>` tag.
    public var hasIndexableContent: Bool {
        if let description, !description.isEmpty { return true }
        return !labels.isEmpty
    }
}
